<?php

namespace Application\PlanningPokerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StoryEstimateByUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryEstimateByUserRepository extends EntityRepository
{
}
