<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121225051617 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE invitation (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(6) NOT NULL, email VARCHAR(255) NOT NULL, sent TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE notification__message CHANGE body body LONGTEXT NOT NULL COMMENT '(DC2Type:json)'");
        $this->addSql("ALTER TABLE media__media CHANGE provider_metadata provider_metadata LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json)'");
        $this->addSql("ALTER TABLE media__media_audit CHANGE provider_metadata provider_metadata LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json)'");
        $this->addSql("ALTER TABLE fos_user_user ADD invitation_id INT NOT NULL, CHANGE facebook_data facebook_data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json)', CHANGE twitter_data twitter_data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json)', CHANGE gplus_data gplus_data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json)'");
        $this->addSql("ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D761A35D7AF0 FOREIGN KEY (invitation_id) REFERENCES invitation (id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_C560D761A35D7AF0 ON fos_user_user (invitation_id)");
        $this->addSql("ALTER TABLE fos_user_user_audit ADD invitation_id INT DEFAULT NULL, CHANGE facebook_data facebook_data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json)', CHANGE twitter_data twitter_data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json)', CHANGE gplus_data gplus_data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json)'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D761A35D7AF0");
        $this->addSql("DROP TABLE invitation");
        $this->addSql("DROP INDEX UNIQ_C560D761A35D7AF0 ON fos_user_user");
        $this->addSql("ALTER TABLE fos_user_user DROP invitation_id, CHANGE facebook_data facebook_data LONGTEXT DEFAULT NULL, CHANGE twitter_data twitter_data LONGTEXT DEFAULT NULL, CHANGE gplus_data gplus_data LONGTEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user_user_audit DROP invitation_id, CHANGE facebook_data facebook_data LONGTEXT DEFAULT NULL, CHANGE twitter_data twitter_data LONGTEXT DEFAULT NULL, CHANGE gplus_data gplus_data LONGTEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE media__media CHANGE provider_metadata provider_metadata LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)'");
        $this->addSql("ALTER TABLE media__media_audit CHANGE provider_metadata provider_metadata LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)'");
        $this->addSql("ALTER TABLE notification__message CHANGE body body LONGTEXT NOT NULL");
    }
}
