<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121226075629 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE session_peoples (session_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_DBF3DEC6613FECDF (session_id), INDEX IDX_DBF3DEC6A76ED395 (user_id), PRIMARY KEY(session_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE session_peoples ADD CONSTRAINT FK_DBF3DEC6613FECDF FOREIGN KEY (session_id) REFERENCES Session (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE session_peoples ADD CONSTRAINT FK_DBF3DEC6A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE session_peoples");
    }
}
