<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121227143102 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE session ADD owner_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE session ADD CONSTRAINT FK_1FF9EC487E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)");
        $this->addSql("CREATE INDEX IDX_1FF9EC487E3C61F9 ON session (owner_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Session DROP FOREIGN KEY FK_1FF9EC487E3C61F9");
        $this->addSql("DROP INDEX IDX_1FF9EC487E3C61F9 ON Session");
        $this->addSql("ALTER TABLE Session DROP owner_id");
    }
}
