<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121226061540 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE story ADD session_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE story ADD CONSTRAINT FK_2A972B3C613FECDF FOREIGN KEY (session_id) REFERENCES Session (id)");
        $this->addSql("CREATE INDEX IDX_2A972B3C613FECDF ON story (session_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Story DROP FOREIGN KEY FK_2A972B3C613FECDF");
        $this->addSql("DROP INDEX IDX_2A972B3C613FECDF ON Story");
        $this->addSql("ALTER TABLE Story DROP session_id");
    }
}
