<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121224212849 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE invitation ADD user_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE invitation ADD CONSTRAINT FK_F11D61A2A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_F11D61A2A76ED395 ON invitation (user_id)");
        $this->addSql("ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D761A35D7AF0");
        $this->addSql("DROP INDEX UNIQ_C560D761A35D7AF0 ON fos_user_user");
        $this->addSql("ALTER TABLE fos_user_user DROP invitation_id");
        $this->addSql("ALTER TABLE fos_user_user_audit DROP invitation_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fos_user_user ADD invitation_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D761A35D7AF0 FOREIGN KEY (invitation_id) REFERENCES invitation (id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_C560D761A35D7AF0 ON fos_user_user (invitation_id)");
        $this->addSql("ALTER TABLE fos_user_user_audit ADD invitation_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE invitation DROP FOREIGN KEY FK_F11D61A2A76ED395");
        $this->addSql("DROP INDEX UNIQ_F11D61A2A76ED395 ON invitation");
        $this->addSql("ALTER TABLE invitation DROP user_id");
    }
}
