<?php

namespace Application\Sonata\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends EntityRepository
{
    public function findUnusedInvitationByCode($code)
    {
        $invitation = $this->findOneByCode($code);
        if(false == is_null($invitation))
        {
            if (is_null($invitation->getUser()))
            {
                return $invitation;
            }
        }
        return null;
    }
}
